<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pokemon;

class PokemonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Lista de 150 pokémon de generación 1
        $pokemonData = [
            ['pokedex_id' => 1, 'name' => 'Bulbasaur', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png'],
            ['pokedex_id' => 2, 'name' => 'Ivysaur', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png'],
            ['pokedex_id' => 3, 'name' => 'Venusaur', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png'],
            ['pokedex_id' => 4, 'name' => 'Charmander', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png'],
            ['pokedex_id' => 5, 'name' => 'Charmeleon', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png'],
            ['pokedex_id' => 6, 'name' => 'Charizard', 'type' => 'fire,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png'],
            ['pokedex_id' => 7, 'name' => 'Squirtle', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png'],
            ['pokedex_id' => 8, 'name' => 'Wartortle', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png'],
            ['pokedex_id' => 9, 'name' => 'Blastoise', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png'],
            ['pokedex_id' => 10, 'name' => 'Caterpie', 'type' => 'bug', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png'],
            ['pokedex_id' => 11, 'name' => 'Metapod', 'type' => 'bug', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png'],
            ['pokedex_id' => 12, 'name' => 'Butterfree', 'type' => 'bug,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png'],
            ['pokedex_id' => 13, 'name' => 'Weedle', 'type' => 'bug,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png'],
            ['pokedex_id' => 14, 'name' => 'Kakuna', 'type' => 'bug,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png'],
            ['pokedex_id' => 15, 'name' => 'Beedrill', 'type' => 'bug,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png'],
            ['pokedex_id' => 16, 'name' => 'Pidgey', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png'],
            ['pokedex_id' => 17, 'name' => 'Pidgeotto', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png'],
            ['pokedex_id' => 18, 'name' => 'Pidgeot', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png'],
            ['pokedex_id' => 19, 'name' => 'Rattata', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png'],
            ['pokedex_id' => 20, 'name' => 'Raticate', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png'],
            ['pokedex_id' => 21, 'name' => 'Spearow', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png'],
            ['pokedex_id' => 22, 'name' => 'Fearow', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png'],
            ['pokedex_id' => 23, 'name' => 'Ekans', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png'],
            ['pokedex_id' => 24, 'name' => 'Arbok', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png'],
            ['pokedex_id' => 25, 'name' => 'Pikachu', 'type' => 'electric', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png'],
            ['pokedex_id' => 26, 'name' => 'Raichu', 'type' => 'electric', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png'],
            ['pokedex_id' => 27, 'name' => 'Sandshrew', 'type' => 'ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png'],
            ['pokedex_id' => 28, 'name' => 'Sandslash', 'type' => 'ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png'],
            ['pokedex_id' => 29, 'name' => 'Nidoran♀', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png'],
            ['pokedex_id' => 30, 'name' => 'Nidorina', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png'],
            ['pokedex_id' => 31, 'name' => 'Nidoqueen', 'type' => 'poison,ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png'],
            ['pokedex_id' => 32, 'name' => 'Nidoran♂', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png'],
            ['pokedex_id' => 33, 'name' => 'Nidorino', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png'],
            ['pokedex_id' => 34, 'name' => 'Nidoking', 'type' => 'poison,ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png'],
            ['pokedex_id' => 35, 'name' => 'Clefairy', 'type' => 'fairy', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png'],
            ['pokedex_id' => 36, 'name' => 'Clefable', 'type' => 'fairy', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png'],
            ['pokedex_id' => 37, 'name' => 'Vulpix', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png'],
            ['pokedex_id' => 38, 'name' => 'Ninetales', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png'],
            ['pokedex_id' => 39, 'name' => 'Jigglypuff', 'type' => 'normal,fairy', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png'],
            ['pokedex_id' => 40, 'name' => 'Wigglytuff', 'type' => 'normal,fairy', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png'],
            ['pokedex_id' => 41, 'name' => 'Zubat', 'type' => 'poison,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png'],
            ['pokedex_id' => 42, 'name' => 'Golbat', 'type' => 'poison,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png'],
            ['pokedex_id' => 43, 'name' => 'Oddish', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png'],
            ['pokedex_id' => 44, 'name' => 'Gloom', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png'],
            ['pokedex_id' => 45, 'name' => 'Vileplume', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png'],
            ['pokedex_id' => 46, 'name' => 'Paras', 'type' => 'bug,grass', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png'],
            ['pokedex_id' => 47, 'name' => 'Parasect', 'type' => 'bug,grass', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png'],
            ['pokedex_id' => 48, 'name' => 'Venonat', 'type' => 'bug,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png'],
            ['pokedex_id' => 49, 'name' => 'Venomoth', 'type' => 'bug,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png'],
            ['pokedex_id' => 50, 'name' => 'Diglett', 'type' => 'ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png'],
            ['pokedex_id' => 51, 'name' => 'Dugtrio', 'type' => 'ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png'],
            ['pokedex_id' => 52, 'name' => 'Meowth', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png'],
            ['pokedex_id' => 53, 'name' => 'Persian', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png'],
            ['pokedex_id' => 54, 'name' => 'Psyduck', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png'],
            ['pokedex_id' => 55, 'name' => 'Golduck', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png'],
            ['pokedex_id' => 56, 'name' => 'Mankey', 'type' => 'fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png'],
            ['pokedex_id' => 57, 'name' => 'Primeape', 'type' => 'fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png'],
            ['pokedex_id' => 58, 'name' => 'Growlithe', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png'],
            ['pokedex_id' => 59, 'name' => 'Arcanine', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png'],
            ['pokedex_id' => 60, 'name' => 'Poliwag', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png'],
            ['pokedex_id' => 61, 'name' => 'Poliwhirl', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png'],
            ['pokedex_id' => 62, 'name' => 'Poliwrath', 'type' => 'water,fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png'],
            ['pokedex_id' => 63, 'name' => 'Abra', 'type' => 'psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png'],
            ['pokedex_id' => 64, 'name' => 'Kadabra', 'type' => 'psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png'],
            ['pokedex_id' => 65, 'name' => 'Alakazam', 'type' => 'psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png'],
            ['pokedex_id' => 66, 'name' => 'Machop', 'type' => 'fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png'],
            ['pokedex_id' => 67, 'name' => 'Machoke', 'type' => 'fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png'],
            ['pokedex_id' => 68, 'name' => 'Machamp', 'type' => 'fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png'],
            ['pokedex_id' => 69, 'name' => 'Bellsprout', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png'],
            ['pokedex_id' => 70, 'name' => 'Weepinbell', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png'],
            ['pokedex_id' => 71, 'name' => 'Victreebel', 'type' => 'grass,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png'],
            ['pokedex_id' => 72, 'name' => 'Tentacool', 'type' => 'water,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png'],
            ['pokedex_id' => 73, 'name' => 'Tentacruel', 'type' => 'water,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png'],
            ['pokedex_id' => 74, 'name' => 'Geodude', 'type' => 'rock,ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png'],
            ['pokedex_id' => 75, 'name' => 'Graveler', 'type' => 'rock,ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png'],
            ['pokedex_id' => 76, 'name' => 'Golem', 'type' => 'rock,ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png'],
            ['pokedex_id' => 77, 'name' => 'Ponyta', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png'],
            ['pokedex_id' => 78, 'name' => 'Rapidash', 'type' => 'fire', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png'],
            ['pokedex_id' => 79, 'name' => 'Slowpoke', 'type' => 'water,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png'],
            ['pokedex_id' => 80, 'name' => 'Slowbro', 'type' => 'water,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png'],
            ['pokedex_id' => 81, 'name' => 'Seel', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png'],
            ['pokedex_id' => 82, 'name' => 'Dewgong', 'type' => 'water,ice', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png'],
            ['pokedex_id' => 83, 'name' => 'Shellder', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png'],
            ['pokedex_id' => 84, 'name' => 'Cloyster', 'type' => 'water,ice', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png'],
            ['pokedex_id' => 85, 'name' => 'Gastly', 'type' => 'ghost,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png'],
            ['pokedex_id' => 86, 'name' => 'Haunter', 'type' => 'ghost,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png'],
            ['pokedex_id' => 87, 'name' => 'Gengar', 'type' => 'ghost,poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png'],
            ['pokedex_id' => 88, 'name' => 'Onix', 'type' => 'rock,ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png'],
            ['pokedex_id' => 89, 'name' => 'Drowzee', 'type' => 'psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png'],
            ['pokedex_id' => 90, 'name' => 'Hypno', 'type' => 'psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png'],
            ['pokedex_id' => 91, 'name' => 'Krabby', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png'],
            ['pokedex_id' => 92, 'name' => 'Kingler', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png'],
            ['pokedex_id' => 93, 'name' => 'Voltorb', 'type' => 'electric', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png'],
            ['pokedex_id' => 94, 'name' => 'Electrode', 'type' => 'electric', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png'],
            ['pokedex_id' => 95, 'name' => 'Exeggcute', 'type' => 'grass,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png'],
            ['pokedex_id' => 96, 'name' => 'Exeggutor', 'type' => 'grass,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png'],
            ['pokedex_id' => 97, 'name' => 'Cubone', 'type' => 'ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png'],
            ['pokedex_id' => 98, 'name' => 'Marowak', 'type' => 'ground', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png'],
            ['pokedex_id' => 99, 'name' => 'Hitmonlee', 'type' => 'fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png'],
            ['pokedex_id' => 100, 'name' => 'Hitmonchan', 'type' => 'fighting', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png'],
            ['pokedex_id' => 101, 'name' => 'Lickitung', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png'],
            ['pokedex_id' => 102, 'name' => 'Koffing', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png'],
            ['pokedex_id' => 103, 'name' => 'Weezing', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png'],
            ['pokedex_id' => 104, 'name' => 'Rhyhorn', 'type' => 'ground,rock', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png'],
            ['pokedex_id' => 105, 'name' => 'Rhydon', 'type' => 'ground,rock', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png'],
            ['pokedex_id' => 106, 'name' => 'Chansey', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png'],
            ['pokedex_id' => 107, 'name' => 'Kangaskhan', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png'],
            ['pokedex_id' => 108, 'name' => 'Horsea', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png'],
            ['pokedex_id' => 109, 'name' => 'Seadra', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png'],
            ['pokedex_id' => 110, 'name' => 'Goldeen', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png'],
            ['pokedex_id' => 111, 'name' => 'Seaking', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png'],
            ['pokedex_id' => 112, 'name' => 'Staryu', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png'],
            ['pokedex_id' => 113, 'name' => 'Starmie', 'type' => 'water,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png'],
            ['pokedex_id' => 114, 'name' => 'Mr. Mime', 'type' => 'psychic,fairy', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png'],
            ['pokedex_id' => 115, 'name' => 'Scyther', 'type' => 'bug,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png'],
            ['pokedex_id' => 116, 'name' => 'Jynx', 'type' => 'ice,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png'],
            ['pokedex_id' => 117, 'name' => 'Electabuzz', 'type' => 'electric', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png'],
            ['pokedex_id' => 118, 'name' => 'Magnemite', 'type' => 'electric,steel', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png'],
            ['pokedex_id' => 119, 'name' => 'Magneton', 'type' => 'electric,steel', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png'],
            ['pokedex_id' => 120, 'name' => 'Farfetchd', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png'],
            ['pokedex_id' => 121, 'name' => 'Doduo', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png'],
            ['pokedex_id' => 122, 'name' => 'Dodrio', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png'],
            ['pokedex_id' => 123, 'name' => 'Lickitung', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png'],
            ['pokedex_id' => 124, 'name' => 'Grimer', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png'],
            ['pokedex_id' => 125, 'name' => 'Muk', 'type' => 'poison', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png'],
            ['pokedex_id' => 126, 'name' => 'Shellder', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png'],
            ['pokedex_id' => 127, 'name' => 'Cloyster', 'type' => 'water,ice', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png'],
            ['pokedex_id' => 128, 'name' => 'Rhyhorn', 'type' => 'ground,rock', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png'],
            ['pokedex_id' => 129, 'name' => 'Rhydon', 'type' => 'ground,rock', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png'],
            ['pokedex_id' => 130, 'name' => 'Chansey', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png'],
            ['pokedex_id' => 131, 'name' => 'Kangaskhan', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png'],
            ['pokedex_id' => 132, 'name' => 'Horsea', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png'],
            ['pokedex_id' => 133, 'name' => 'Seadra', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png'],
            ['pokedex_id' => 134, 'name' => 'Goldeen', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png'],
            ['pokedex_id' => 135, 'name' => 'Seaking', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png'],
            ['pokedex_id' => 136, 'name' => 'Staryu', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png'],
            ['pokedex_id' => 137, 'name' => 'Starmie', 'type' => 'water,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png'],
            ['pokedex_id' => 138, 'name' => 'Mr. Mime', 'type' => 'psychic,fairy', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png'],
            ['pokedex_id' => 139, 'name' => 'Scyther', 'type' => 'bug,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png'],
            ['pokedex_id' => 140, 'name' => 'Jynx', 'type' => 'ice,psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png'],
            ['pokedex_id' => 141, 'name' => 'Electabuzz', 'type' => 'electric', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png'],
            ['pokedex_id' => 142, 'name' => 'Magnemite', 'type' => 'electric,steel', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png'],
            ['pokedex_id' => 143, 'name' => 'Magneton', 'type' => 'electric,steel', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png'],
            ['pokedex_id' => 144, 'name' => 'Farfetchd', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png'],
            ['pokedex_id' => 145, 'name' => 'Doduo', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png'],
            ['pokedex_id' => 146, 'name' => 'Dodrio', 'type' => 'normal,flying', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png'],
            ['pokedex_id' => 147, 'name' => 'Ditto', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png'],
            ['pokedex_id' => 148, 'name' => 'Eevee', 'type' => 'normal', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png'],
            ['pokedex_id' => 149, 'name' => 'Vaporeon', 'type' => 'water', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png'],
            ['pokedex_id' => 150, 'name' => 'Mewtwo', 'type' => 'psychic', 'image_url' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png'],
        ];

        // Insertar todos los pokémon
        foreach ($pokemonData as $pokemon) {
            Pokemon::updateOrCreate(
                ['pokedex_id' => $pokemon['pokedex_id']],
                [
                    'name' => $pokemon['name'],
                    'type' => $pokemon['type'],
                    'image_url' => $pokemon['image_url'],
                ]
            );
        }
    }
}
